# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: User Operation Request
      id: userOp
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://f1dcf3d2-d4e7-45f4-ac93-5394986d1fb4.webhook.eus.azure-automation.net/webhooks?token=alY0%2bX8%2fv%2fYrFP65PU0psQrwPoYWsTKIBdQgx9bF5v4%3d
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"userop": "Delete", "username": "fortilab22","odlconfig": "sdwan-lab"}'

    - name: User Operation Response
      run: |
        echo ${{ steps.userOp.outputs.response }}
        echo ${{ steps.userOp.outputs.headers }}
        echo ${{ fromJson(steps.userOp.outputs.response).JobIds }}
